---
- name: Initial system setup
  gather_facts: True
  become: True
  hosts: all # Yes please use the -l flag for this
  tasks:
    - name: Initial Ansible setup
      ansible.builtin.import_role:
        role: initial-setup
      tags: initial-setup
