---
- name: Reload firewalld
  ansible.builtin.service:
    name: firewalld
    state: reloaded

- name: Restart ufw
  ansible.builtin.service:
    name: ufw
    state: restarted

- name: Reload openssh-server
  ansible.builtin.service:
    name: sshd
    state: reloaded

- name: Restart systemd-journald
  ansible.builtin.service:
    name: systemd-journald
    state: restarted
