---
- name: Reload firewalld
  ansible.builtin.service:
    name: firewalld
    state: reloaded

- name: Restart ufw
  ansible.builtin.service:
    name: ufw
    state: restarted

- name: Reload Fedora openssh-server
  ansible.builtin.service:
    name: sshd
    state: reloaded

- name: Reload Debian openssh-server
  ansible.builtin.service:
    name: ssh
    state: reloaded

- name: Restart systemd-journald
  ansible.builtin.service:
    name: systemd-journald
    state: restarted
